[#antidoping]
== ANTIDOPING

=== PŘIJETÍ

. ČHS přijal světová antidopingová pravidla.

=== POUŽITÍ

. Antidopingová pravidla se vztahují na všechny soutěže pořádané pod záštitou ČHS. 
. Jakákoliv osoba – jako sportovec, trenér, soutěžní činitel, člen lékařského nebo ošetřovatelského personálu - která se přihlásí, připravuje se nebo se účastní těchto soutěží, je chápána jako někdo, kdo souhlasil s respektováním a podřízením se antidopingovým pravidlům a bodu <<#prestupky-a-sankce-doping>>.

=== PŘÍSLUŠNÉ ORGÁNY V RÁMCI ČHS

. Orgánem ČHS, který se zabývá prosazováním antidopingových pravidel v lezeckých soutěžích – které zahrnují lezení na obtížnost, boulder, lezení na rychlost a Boulder&Obtížnost – je Disciplinární komise ČHS.

[#prestupky-a-sankce-doping]
=== PŘESTUPKY A SANKCE

. S dopingovými přestupky bude nakládáno ve shodě s Antidopingovou politikou Světové antidopingové asociace a s Disciplinárním řádem ČHS.
. Při porušení antidopingových pravidel může závodník ztratit právo startu v soutěžích organizovaných ČHS.  Závodník je povinnen (případně jeho zákonný zástupce) v případě krácení finanční dotace ČHS ze strany poskytovatele dotace, uhradit ČHS škodu v plné výši krácenené částky.
