name: Docker Image CI - Generate PDF using asciidoctor-pdf

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor 
    steps:
    - name: Get build number
      id: get-build
      uses: mlilback/build-number@v1
      with:
        base: 5
        run-id: ${{ github.run_number }}

    - name: Get current date
      id: date
      run: |
        echo "NOW=$(date +'%d.%m.%Y')" >> $GITHUB_ENV
        echo "VERSION=1.4.$(($BUILD_NUMBER))" >> $GITHUB_ENV

    - name: Print build number

      run: |
        echo "Number: ${{ steps.get-build.outputs.build-number }}"
        echo "Version: $VERSION"

    - uses: actions/checkout@v4
      
    - name: Run asciidoctor-pdf
      run: asciidoctor-pdf -r asciidoctor-mathematical -a compress -a mathematical-format=svg -a revdate=$NOW -a revnumber=$VERSION src/asciidoc/*.adoc
    
    - name: Archive generated pdf's
      uses: actions/upload-artifact@v4
      with:
        name: pravidla-pdf-${{ steps.get-build.outputs.build-number }}
        path: src/asciidoc/*.pdf
      
       
